version: '3'
services:
  web:
    container_name: ecommerce
    restart: on-failure
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27017:27017'
